spring:
  application:
    name: ntt-ms-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ntt-ms-customers
          uri: lb://ntt-ms-customers
          predicates:
            - Path=/customers/**
        - id: accounts
          uri: lb://ntt-ms-accounts
          predicates:
            - Path=/accounts/**

server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka